#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    acme-minio-9090-http:
      entrypoints:
        - http-9089
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-minio-9090"
      tls: false
      # middlewares:
      #   - "acme-redirectHttps"
    acme-minio-10101-http:
      entrypoints:
        - http-10100
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-minio-10101"
      tls: false
      # middlewares:
      #   - "acme-redirectHttps"
    acme-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-web-80"
      tls: false
      # middlewares:
      #   - "acme-redirectHttps"
    acme-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-web-8025"
      tls: false
      # middlewares:
      #   - "acme-redirectHttps"
    acme-web-5173-http:
      entrypoints:
        - http-5172
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-web-5173"
      tls: false
      # middlewares:
      #   - "acme-redirectHttps"
    acme-web-8080-http:
      entrypoints:
        - http-8080
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-web-8080"
      tls: false
      # middlewares:
      #   - "acme-redirectHttps"
    acme-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-xhgui-80"
      tls: false
      # middlewares:
      #   - "acme-redirectHttps"
    
    
    
    acme-minio-9090-https:
      entrypoints:
        - http-9090
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-minio-9090"
      
      tls: true
      
    acme-minio-10101-https:
      entrypoints:
        - http-10101
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-minio-10101"
      
      tls: true
      
    
    
    
    
    acme-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-web-80"
      
      tls: true
      
    acme-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-web-8025"
      
      tls: true
      
    acme-web-5173-https:
      entrypoints:
        - http-5173
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-web-5173"
      
      tls: true
      
    acme-web-8080-https:
      entrypoints:
        - http-8081
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-web-8080"
      
      tls: true
      
    
    acme-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^acme\.ddev\.site$`)
      
      service: "acme-xhgui-80"
      
      tls: true
      
    

  middlewares:
    acme-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    acme-minio-9090:
      loadbalancer:
        servers:
          - url: http://ddev-acme-minio:9090
        
    acme-minio-10101:
      loadbalancer:
        servers:
          - url: http://ddev-acme-minio:10101
        
    
    
    acme-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-acme-web:80
        
    acme-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-acme-web:8025
        
    acme-web-5173:
      loadbalancer:
        servers:
          - url: http://ddev-acme-web:5173
        
    acme-web-8080:
      loadbalancer:
        servers:
          - url: http://ddev-acme-web:8080
        
    
    
    
    
    acme-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-acme-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/acme.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/acme.key